### ISSUE TITLE
geoBlocking

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#10]
Range for this? Location only?

**Comment by tormodv** [comment]
Wrong name, I tried to write the issue without having the model in front of me. It is http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#geoBlocking, the current range is xsd:string.

**Comment by kimviljanen** [comment]
Regarding geoblocking I have sometimes been thinking that "blocking" sounds like the wrong word, because typically what is meant is "geo allowing" --- that is, where the content IS available and not was is blocked out. "AvailableIn=Europe" would describe the intention better than "GeoBlocking=OtherUniversumExceptEurope".

**Comment by JuergenGrupp** [comment]
Editorial Committee: Use skos:Concept as range, because values are very specific to each media enterprise.    The attribute should be associated with the publication event, based on the rights (licences) of the editorial objects

**Comment by kimviljanen** [comment]
Random idea this morning: would it be clearer to name it ”geoBlockedTo” ?

**Comment by JuergenGrupp** [comment]
> 

English wikipedia explains geo-blocking as "checking a users IP-address against a blacklist or whitelist". Would it be a good idea to have two attributes like "geoBlockingWhitelist" and "geoBlockingBlacklist"? 
Then of course, it could be a list of countries ("Germany, Austria, Switzerland, France") or a list of skos:Concepts (like "EWS"="Europe without Switzerland").
