### ISSUE TITLE
Reorganize the Asset and its subclasses.

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#131]
Reorganize the Asset and its subclasses.
<img width="280" alt="Skjermbilde 2022-05-20 kl  09 06 21" src="https://user-images.githubusercontent.com/12021922/169472838-8d3d57f8-dcb2-4bfd-855f-7f38d8d53372.png">
Data about value and related to rights and contracts -> Asset
Descriptive metadata, dcterms like, -> BusinessObject
Data about the adaptation of an intellectual work for broadcast -> BibliographicalObject
Data about the relation to publishingEvents, manifestations in files, timeline information and rundown -> Editorial Object
Data about Series and brands, that not have a separate manifestation as an media file. -> Group

Delete the Version class. Version is a relationship.

One last question: Is it constructive to have the asset as the mother of the subclasses? Can we start the three with the Business object instead?

**Comment by JuergenGrupp** [comment]
This is the tree from the last published CCDM 2.3, obviously quite different:
![image](https://user-images.githubusercontent.com/80782611/169491786-40dc714a-b3f2-41d9-a451-78842ec164d7.png)
- There is no BusinessObject anymore. I agree that we do not need both: Asset and BusinessObject. But it's hard to decide, which one is obsolete: Asset immediately refers to value, rights and contracts. That's good. BusinessObject refers to almost anything but is often associated with data objects in programming. Don't know whether that is good or bad? Personally, I am inclined to use Asset instead of BusinessObject.
- I don't see why we would need BibliographicalObject. Probably other existing ontologies would represent that concept much better and then we should link to those?
- I am not shure about the Group. Tormod's explanation sounds reasonable: Groups do not have a specific manifestation as a media resource. But: if they have similar properties in almost all other aspects (e.g. Titles, sequence information, publicationEvents, related ProductionJobs and Agents), then they should be similar to an EditorialObject, that simply happens to not (yet) have a related Media Resource. Therefore, I think "Series", "Seasons", Collections" should be sub-classes of EditorialObjects, not sister-classes.
- "Brand" is different from Series, Seasons and Collections. I think it covers far more than a group of EditorialObjects. Here it seems to be a collection of EditorialObjects. So why not call it a Collection and assign a Brand to it? Brands may be assigned to any EditorialObject.
-  Deleting Version is right imho.

**Comment by tormodv** [comment]
The Business object appeared in the EBU Core RDF.  I have used the class for descriptive metadata, think Dublin Core. 
If we remove BibliographicalObject and move the group class as a subclass of the Editorial object, the properties can be transferred to the editorial object class. If we do this, we are back to the original CCDM layout (with some more subclasses.)

BibliographicalObject and the two sub-classes have only one property so we are perhaps better off deleting it.
