### ISSUE TITLE
:isReferencedBy

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#142]
Today this is a relation between a MediaResource and an Editorial object.
I think this doesn't seem right. In the Media archive in NRK, we used this to refer to other identificators, like the identification from the publisher of the CD. This will make this a relation between a BusinessObject and an Identifier.

In Dublin Core, the definition is "A related resource that references, cites, or otherwise points to the described resource."
In this case, a relation between two BusinessObjects will be in order.

**Comment by tormodv** [comment]
In its current state, this appears as a bug. How do we solve it? @JuergenGrupp

**Comment by JuergenGrupp** [comment]
I agree that "isReferencedBy" should not be between a MediaResource and an EditorialObject. But I am not sure, whether it should  be between BusinessObjects: 
1. "isReferencedBy" can be interpreted very generally, so that e.g. even Assets should probably have this property and thus the meaning becomes so generic that it adds very little semantic value for any business logic to exploit.
2. the Dublin Core definition implies a more specific meaning using the terms "references", "cites". I understand this as a relation existing for content reasons, not for technical reasons. Therefore, I would rather see "isReferencedBy" as a relation between EditorialObjects (and between BibliographicalObjects, if we keep them in the model at all. That's another question ...).
3. If we also need a relation that points from one Resource to another, we should give it a meaning that's more specific and maybe another name, e.g. "isVersionOf", "dependsOn", to improve the semantic value of such a relation for any business logic that builds upon it.
