### ISSUE TITLE
Introducing Engagement to model any form of participation and contribution of an Agent for an Asset

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ccdm#175]
We have currently two types of modelling participation and contribution of Agents for an Asset with major drawbacks:

1. by contribution specific properties of Agent, e.g.
an Asset -hasCreator-> an Agent
an Asset -hasProducer-> an Agent
Drawback: while this pattern is simple and feasible for the most common roles, it will require to change the model with any new role popping up.

2. by attaching a Role to an Agent, which is related to an Asset: 
an Asset -hasParticipatingAgent-> an Agent -hasRole-> a Role
Drawback: the same person participating in two films with two different roles must be represented by two Agent-objects to ensure correct assignment of the role to the Asset

Conclusion: The "Role" must be modelled as a flexible relation between Asset and Agent.

Proposal: Introduce a new class "Engagement" that can connect an Asset with an Agent and has a property of type skos:Concept to describe the Role with a taxonomy. This new class introduces the advantage that many more expressive properties can be added, such as "impliesRight" to connect to Rights emerging from the type of Engagement, "executedInProductionJob" to connect to the ProductionJob or "usesArtefact" to connect to Artefact. See graph for proposal.

![image](https://user-images.githubusercontent.com/80782611/185959184-11a62b52-e968-4a33-b1c1-6d2a07edc270.png)

**Comment by kimviljanen** [comment]
Some random thoughts:
- I also think the Role must be a class and Skos vocabulary sounds like a good approach to model the constantly groving list of potential roles a person can have in a production.
- What about roles that are between Agents and e.g. EditorialWorks such as The director of the program X?
- What about outcomes that are not Production Job kind of work, but the outcome is e.g. an instance of EditorialWork such as a Series or Article or Post?
- What about roles that exist outside of the contractual space? Such as ”thank you to…”
- ”Engagement” could this be easier to understand if it would have the class name Role?

**Comment by JuergenGrupp** [comment]
My comments to Kim's quotes:

> I also think the Role must be a class and Skos vocabulary sounds like a good approach to model the constantly groving list of potential roles a person can have in a production.

Agreed.

> What about roles that are between Agents and e.g. EditorialWorks such as The director of the program X?

An instance of Engagement (type=director) connects an Agent (name=Woody Allen) and an EditorialWork (type=Movie, title=Manhattan).

> What about outcomes that are not Production Job kind of work, but the outcome is e.g. an instance of EditorialWork such as a Series or Article or Post?

An instance of ProductionJob is **not** mandatory to describe the Engagement of an Agent with respect to an EditorialObject. You can leave it out, if you wish. However, ProductionJob can represent very generic activities and it can be grouped in hierarchies. Why would a Series, an Article or a Post not be the result of such a ProductionJob?

> What about roles that exist outside of the contractual space? Such as ”thank you to…”

An instance of Contract is **not** mandatory to describe the Engagement of an Agent with respect to an EditorialObject. You can leave it out, if you wish. However, a person's role/engagement that is mentioned in a movie's end credits and thanked for whatever cause, could be represented by a specific skos:Concept, e.g. “advicing”, “supporting”, …

> ”Engagement” could this be easier to understand if it would have the class name Role?

I am always open to discuss better naming. In this case I chose “Engagement” because the explanation in the Merriam-Webster dictionary appealed to me: “a job or period of employment especially as a performer”. It expresses the time-bounded nature of the contribution and covers everybody who is employed (Crew members, pre-production staff, actors…), while also highlighting performers. Interested to hear what others think ...

**Comment by kimviljanen** [comment]
Thanks for the detailed answers and comments! It helped me to understand the proposal better and I agree on your reasoning. One comment though:

> Why would a Series, an Article or a Post not be the result of such a ProductionJob?
It depends on what all activities are considered to be ProductionJobs. For example, are tasks that are done before a project (i.e. production) considered as ProductionJobs? Are preproduction jobs Production Jobs? Is activites done by e.g. the Editor in Chief of the news department considered to be ProductionJobs (management people tend to output e.g. decisions of creating a new Series).

**Comment by tormodv** [comment]
Thank you for the proposal.

A few of the relations are already in the model with different names. Why do we need a name change?
Until now, we have been quite restrictive on defining relations with an inverse relationship. 

For example, a ProductionJob is based on an EditorialObject. We have this relationship. I have never experienced a production job that results in a production job.
A production job has an output Resource or Essence. We have already defined this. An inverse relationship is not necessary as the production process for media made by others usually are unknown.

We should also check the rationale for the other relationships; some of them may already exist.

> by contribution specific properties of Agent, e.g.
an Asset -hasCreator-> an Agent
an Asset -hasProducer-> an Agent
Drawback: while this pattern is simple and feasible for the most common roles, it will require to change the model with any new role popping up.

**This is not the current way to do it.**

We have, in the tradition of Dublin core, three central relationships. Creator, Publisher and Contributor.
Each of them can be enhanced with a role. (Which is already an instance of skos:Consept)

So I can't see why we need a change for every new role popping up. The work done until now on EBU Core has not been that stupid. We already have the proposed concept, that you are calling Engagement. In EBU Core this is what the Agent class is used for.

<img width="642" alt="Skjermbilde 2022-08-28 kl  17 52 58" src="https://user-images.githubusercontent.com/12021922/187083107-22e58c32-d194-4d52-80f3-96c02b97d912.png">


> by attaching a Role to an Agent, which is related to an Asset:
an Asset -hasParticipatingAgent-> an Agent -hasRole-> a Role
Drawback: the same person participating in two films with two different roles must be represented by two Agent-objects to ensure correct assignment of the role to the Asset

Just 89% right, see above.

We have a solution for this problem, but you can find it. Then the current solution is wrong 😄 
The use of the agentclass in EBUCore is a bit exotic, so let rename it into something that don't have to explain for each user.

<img width="623" alt="Skjermbilde 2022-08-28 kl  18 11 05" src="https://user-images.githubusercontent.com/12021922/187083784-79067043-abff-420d-9ec7-8f4ae5cdb20b.png">


So I like the proposal, but we have to work a bit on it, so we can reuse the parts that already is present in  the model, if there are something useful.


I think the diagram need the role class present for clarity.

The proposal have a more common use of the Agent class, which is good.

And I remember when this came into the model, we tried to solve the problem for planning, where you needed the function and the agent was unknown. It was late in the afternoon and we should have used more time then 😄 

I think we should add the playOut also to the diagram, because we have publishing rights versus other rights.

**Comment by kimviljanen** [comment]
RoleEngagement anybody? :)

**Comment by JuergenGrupp** [comment]
Thank you for your feedback!

All your ideas helped me a lot to better understand what is already there and should be reused. So I tried to improve the proposal (definitely not the last improvement). Check the graph and find explanations below. Please comment!

![image](https://user-images.githubusercontent.com/80782611/190246409-dac19d9c-0ecc-4091-a4cb-a69477168dda.png)

Please note:
- the class Agent could be used simply as the super class for Person, Organisation and Animal and not serve anymore as connecting class between EditorialObject and Role as in Tormods graph.
-  the class Role could take over what I called Engagement. This way Roles could be added to EditorialObjects, and if needed also to ProductionJobs
- the property hasProductionJobContributor used to point to Agent, but now it points to Role
- the property hasRole could be sub-classed by hasCrew/Cast/Staff/Role, if the skos:Concept for Role distinguishes the same 3 classifications
- I tried to reuse the existing object properties
- I placed ProductionDevice instead of Artefact in the graph, just because it seemed to be more important in this context
- I added PublicationEvent to imply that the Rights cover a wide range (there are many subclasses already. Some of them cover PublicationEvents, some cover EditorialObjects. That needs to be examined separately)

**Comment by tormodv** [comment]
It is right that the role is the relationship between some programme and a Agent.
I think we can call hasRole for hasContributor, with the specialisation hasPublisher and hasCreator. (heritage from DublinCore)

We also have the relationship that publicationEvent publishes some editorial object, I think we can keep this too.
Same for the existing relations EO and production job.

**Comment by tormodv** [comment]
By the way. I think we need to publish an updated role list in skos format.

**Comment by tormodv** [comment]
@JuergenGrupp 
**role hasRghts**  can we say ** role bringsRights Rights** instead? The rights appear as a consequence of the engagement.

**Comment by JuergenGrupp** [comment]
> role hasRghts can we say ** role bringsRights Rights** instead? The rights appear as a consequence of the engagement.
Ok.

>Should we rename ebuccdm:hasPJContributor to :hasContributor?
Ok.
