### ISSUE TITLE
add Part as ec:Part

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#28]

**Comment by JuergenGrupp** [comment]
Are shots always parts of scenes? How about a “single-shot movie”, that definitely has many scenes, but only one shot.

**Comment by JuergenGrupp** [comment]
Not sure about the best wording: 
Description of Shot: “A film sequence photographed continuously …” 
Shouldn't it rather read: “…film segment …”

**Comment by JuergenGrupp** [comment]
Not shure about the best wording:
Description of Take is complicated. I'd rather separate video and audio and remove “at one time” because the term “continuously” is already there.
Should it be changed to: “A particular version of either a) a scene or sequence of vision photographed continuously or b) a sequence of sound recorded continuously.” ?
