### ISSUE TITLE
Adresses

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#60]
:locationAddressArea <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locationAddressArea>
:locationAddressCountry <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locationAddressCountry>
:locationAddressLine <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locationAddressLine>
:locationAddressLocality <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locationAddressLocality>
:locationAddressPostalCode <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locationAddressPostalCode>

This is the way we are describing addresses. And things are fine, but :locationAddressLine is very often broken down to more specific fields, where an address line is more of an option.
Other standards operate with address name, i.e. the street or square, house number, entrance letter, floor etc. 

Should we also split the address line?

**Comment by alexander-schulze** [comment]
I noticed the properties being sub-properties of “Address”: Actually, sub-properties are a **specializations** of their parents, here the sub-properties are modelled rather as items of an address. For me, the term “Address” would rather be appropriate for a complete address. The question here is, if there is a use case, e.g. to find all individuals that have an item of an address. If so, I would rename “Address” to “Address Item”, for instance. If not, I would remove “Address” and use the current sub-properties as root-data-properties. Otherwise a quite huge set of unrequired triples will be inferred, when we use a RDFS(+) reasoner. This would unnecessarily increase the size of the GraphDB.

**Comment by alexander-schulze** [comment]
In general, to me it appears reasonable to explicitly split address information into its various parts like street and street number. Usually, it is easier to join/combine data on demand other than to split it. So yes, in case of the “address line” I vote for explicitly splitting it into street, street number, building, floor etc. (the latter ones being optional). For “area” maybe “province”, “state” or “county” might be more comprehensible terms (TBD).

I noticed the properties being sub-properties of “Address”: Actually, sub-properties are a **specializations** of their parents, here the sub-properties are modelled rather as items of an address. For me, the term “Address” would rather be appropriate for a complete address. The question here is, if there is a use case, e.g. to find all individuals that have an item of an address. If so, I would rename “Address” to “Address Item”, for instance. If not, I would remove “Address” and use the current sub-properties as root-data-properties. Otherwise a quite huge set of unrequired triples will be inferred, when we use a RDFS(+) reasoner. This would unnecessarily increase the size of the GraphDB.
